### PR TITLE
Added authetixation and authorization

### PR DESCRIPTION
**Pull request by NureMerkulovArsenii**
Working endpoints:

- api/account/login [POST]
- api/account/register [POST]
- api/account/refresh [GET]

Login data comes with the request body, the refresh token stays in HttpOnly Cookie, and the access token is contained in the header as an Authorization param. mind that the token value in the header has a "Bearer" at the string start. You need to remove it.

### CODE REVIEW

**Review by NureDzabakhidzeDavyd — DISMISSED** [review]
image

Do similiar class JwtSettings

remove Route to HttpGet or remove routes from HttpGet

Can we remove [Obsolete]?

**Comment by NureMerkulovArsenii** [comment]
I don't see the point of using such an approach (getSection) because I think that Approcah with IOptions is better, but if you want to change it , you are welcome))

**Comment by NureMerkulovArsenii** [comment]
fixed refresh token check

**Review by ikew007 — APPROVED** [review]
Finally!

**Review by wher3ver — APPROVED** [review]

**Pull request merged**
