### PR TITLE
Product`s catalogue filtering and pagination.

### PR DESCRIPTION
**Pull request by NureMerkulovArsenii**
I added a controller and a service for the product`s catalogue that can apply pagination and filtering.

### CODE REVIEW

**Review by vanyavidivici — APPROVED** [review]
Excellent!

**Review by NightStrang6r — APPROVED** [review]
Good

**Review by ikew007 — APPROVED** [review]
Cool!!!

**Review by wher3ver — APPROVED** [review]

**Comment by NureDzabakhidzeDavyd** [comment]
Ihttps://www.google.com/search?q=it%27s+the+biggest+piece+of+dog&oq=itsthe+biggest+&aqs=chrome.1.69i57j0i13i512l4j0i22i30l4j0i15i22i30l4j0i22i30l2.3475j0j7&client=ms-android-xiaomi-rev1&sourceid=chrome-mobile&ie=UTF-8#

**Pull request merged**
